title: MiniLappisConf
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://minilappisconf.lappis.rocks" # the base hostname & protocol for your site
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: page
